### ISSUE TITLE
Anonymous users are not allowed to make changes

### ISSUE THREAD

**Issue by alopezmesa** [lucapisciotta/calibre#1]
Hello, thank you very much for your work.
Everything works ok, but, I can't upload new books.
It indicates that I have to login to caliber first, but the option does not appear.
This is the message......

Failed to upload the file: "xxx.epub"
You must be logged in to make changes to the library
-------
Failed to communicate with "/cdb/add-book/3/n/xxx.epub/books", with status: [403 (error)] Forbidden
Anonymous users are not allowed to make changes
-------

Can you have a solution?
Thanks again

**Comment by lucapisciotta** [comment]
Hi, did it work on the old version? I need to try to enable the user database, in this way the option should appears.
Usually i use the client to manage the ebooks and this container only to get them from the eReader.
I'll do some experiments 😊

**Comment by alopezmesa** [comment]
Hello, it is the first of your versions that I try.
The installation as a caliber app in raspbian, works fine outside of
docker, but my project is to pass as many apps as possible to docker; to
detach myself from the operating system.
I've tried a lot of docker-compose and none of them solved it for me.
I just tried the version of "mephistoxol / calibresrv_web" and it is just
what I was looking for.
Thank you very much for your time, I will be watching your progress.

**Comment by lucapisciotta** [comment]
Ok, no problem, i'm trying to use the official source code because the packages in the repositories are using an old version of calibre.

**Comment by lucapisciotta** [comment]
@alopezmesa released a new version with the possibility to add ebooks directly from the WebUI

**Comment by Mallemonade** [comment]
please I am also experiencing the same thing, I want to upload a book through the content server but it always fails and the writing appears as mentioned. Maybe there is a solution, I would be very grateful for it 😓🙏

**Comment by Mallemonade** [comment]
Thanks Luca. I've figured it out. Apparently after setting the settings, I
forgot to restart so the new rules didn't take effect immediately *LOL.
Thanks again for your concern, Luca. Have a Nice day 😻😻😻
